import React, { useEffect, useMemo, useState } from 'react';
import Head from 'next/head';
import {
    Container,
    Typography,
    Box,
    Button,
    TextField,
    Card,
    CardContent,
} from '@mui/material';

const DOWNLOAD_LINKS_KEY = 'secure_download_links';

const readStoredDownloadLinks = () => {
    if (typeof window === 'undefined') return [];
    try {
        const stored = JSON.parse(window.localStorage.getItem(DOWNLOAD_LINKS_KEY) || '[]');
        return Array.isArray(stored) ? stored : [];
    } catch (_error) {
        return [];
    }
};

const DownloadLinksPage = () => {
    const [links, setLinks] = useState([]);
    const [emailFilter, setEmailFilter] = useState('');

    useEffect(() => {
        setLinks(readStoredDownloadLinks());
    }, []);

    const filteredLinks = useMemo(() => {
        const normalizedEmail = emailFilter.trim().toLowerCase();
        if (!normalizedEmail) return links;
        return links.filter((link) => String(link?.userEmail || '').toLowerCase() === normalizedEmail);
    }, [links, emailFilter]);

    return (
        <Container maxWidth="md" sx={{ py: 10 }}>
            <Head>
                <title>Download Links | Guitar Sheets Store</title>
            </Head>

            <Typography variant="h4" gutterBottom fontWeight="bold">
                Your Download Links
            </Typography>

            <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Personal download links are generated by the backend after successful payments and saved locally on this browser.
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Links are tied to the paid order and expire automatically.
            </Typography>

            <TextField
                fullWidth
                label="Filter by Email"
                value={emailFilter}
                onChange={(e) => setEmailFilter(e.target.value)}
                size="small"
                sx={{ mb: 3 }}
            />

            {filteredLinks.length === 0 ? (
                <Typography>No stored download links found for this browser/email.</Typography>
            ) : (
                filteredLinks.map((link, index) => (
                    <Card key={`${link.orderId || 'order'}-${link.productId || 'product'}-${index}`} variant="outlined" sx={{ mb: 2 }}>
                        <CardContent>
                            <Typography variant="subtitle1" fontWeight="bold">
                                {link.title || link.productId}
                            </Typography>
                            <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                                Order: {link.orderId || 'N/A'}
                            </Typography>
                            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                                User: {link.userEmail || 'N/A'}
                            </Typography>
                            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mb: link.isBundle ? 2 : 0 }}>
                                <Button
                                    component="a"
                                    href={link.url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    variant="contained"
                                    color="primary"
                                    sx={{ fontWeight: '900' }}
                                >
                                    Download {String(link.format || (link.isBundle ? 'pdf' : 'file')).toUpperCase()}
                                </Button>
                            </Box>
                            {link.isBundle && Array.isArray(link.sheets) && link.sheets.length > 0 && (
                                <Box sx={{ pl: { xs: 1, sm: 3 }, borderLeft: '3px solid var(--brutal-ink)', mt: 2 }}>
                                    <Typography variant="subtitle2" sx={{ fontWeight: 800, mb: 1, color: 'text.secondary' }}>
                                        Or download individual sheets:
                                    </Typography>
                                    {link.sheets.map((sheet) => (
                                        <Box key={sheet.id} sx={{ mb: 2, p: 1.5, border: '2px solid var(--brutal-ink)', borderRadius: 1, bgcolor: 'var(--brutal-paper)' }}>
                                            <Typography variant="body2" sx={{ fontWeight: 800, mb: 1 }}>
                                                {sheet.title}
                                            </Typography>
                                            <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                                                <Button
                                                    size="small"
                                                    component="a"
                                                    href={`${link.url}&item=${sheet.id}&format=pdf`}
                                                    target="_blank"
                                                    variant="outlined"
                                                    sx={{ py: 0.5, px: 1.5, fontSize: '0.75rem', fontWeight: 800 }}
                                                >
                                                    PDF
                                                </Button>
                                                <Button
                                                    size="small"
                                                    component="a"
                                                    href={`${link.url}&item=${sheet.id}&format=png&labelDisplay=notes`}
                                                    target="_blank"
                                                    variant="outlined"
                                                    sx={{ py: 0.5, px: 1.5, fontSize: '0.75rem', fontWeight: 800 }}
                                                >
                                                    PNG (Notes)
                                                </Button>
                                                <Button
                                                    size="small"
                                                    component="a"
                                                    href={`${link.url}&item=${sheet.id}&format=png&labelDisplay=intervals`}
                                                    target="_blank"
                                                    variant="outlined"
                                                    sx={{ py: 0.5, px: 1.5, fontSize: '0.75rem', fontWeight: 800 }}
                                                >
                                                    PNG (Intervals)
                                                </Button>
                                                <Button
                                                    size="small"
                                                    component="a"
                                                    href={`${link.url}&item=${sheet.id}&format=png&labelDisplay=fingering`}
                                                    target="_blank"
                                                    variant="outlined"
                                                    sx={{ py: 0.5, px: 1.5, fontSize: '0.75rem', fontWeight: 800 }}
                                                >
                                                    PNG (Fingering)
                                                </Button>
                                            </Box>
                                        </Box>
                                    ))}
                                </Box>
                            )}
                        </CardContent>
                    </Card>
                ))
            )}
        </Container>
    );
};

export default DownloadLinksPage;
